os: linux
dist: bionic
language: python
python:
  - "3.7"
cache: pip
branches:
  only:
    - master
    - staging
stages:
  - name: test
    if: type == pull_request
  - name: deploy
    if: type != pull_request
install: skip

jobs:
  include:
    - stage: test
      name: "Test stage"
      script: |
        echo "Run test stage"
    - &deploy-stage
      stage: deploy
      name: "Deploy code to staging servers"
      if: branch = staging
      before_deploy: |
        echo "This is called before deploy"
        echo "Saved before deploy" > before_deploy.result
      script: echo "Starting deployment"
      deploy:
        skip_cleanup: true
        provider: script
        script: |
          echo "Run deploy on staging branch"
          cat before_deploy.result
    - <<: *deploy-stage
      name: "Deploy code to production servers"
      if: branch = master
      deploy:
        provider: script
        script: |
          echo "Run deploy on master branch"
          cat before_deploy.result
